<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'slug' => 'school-management',
                'name_bn' => 'স্কুল ম্যানেজমেন্ট সিস্টেম',
                'name_en' => 'School Management System',
                'tagline_bn' => 'স্কুলের সব কাজ এক প্ল্যাটফর্মে',
                'tagline_en' => 'Run your entire school from one platform',
                'summary_bn' => 'ভর্তি, উপস্থিতি, পরীক্ষার ফলাফল, ফি ও শিক্ষার্থী-অভিভাবক যোগাযোগ — সবকিছু এক জায়গায়।',
                'summary_en' => 'Admissions, attendance, results, fees, and parent communication — all in one place.',
                'features_bn' => [
                    'ভর্তি ও শিক্ষার্থী প্রোফাইল ব্যবস্থাপনা',
                    'দৈনিক উপস্থিতি (ম্যানুয়াল ও বায়োমেট্রিক)',
                    'পরীক্ষা ও রেজাল্ট কার্ড তৈরি',
                    'ফি সংগ্রহ ও ডিউ রিমাইন্ডার (SMS)',
                    'অভিভাবক পোর্টাল ও মোবাইল অ্যাপ',
                    'শিক্ষক বেতন ও HR মডিউল',
                    'ক্লাস রুটিন ও একাডেমিক ক্যালেন্ডার',
                    'রিপোর্ট ও ড্যাশবোর্ড অ্যানালিটিক্স',
                ],
                'features_en' => [
                    'Admission & student profile management',
                    'Daily attendance (manual & biometric)',
                    'Exams & report card generation',
                    'Fee collection with SMS due reminders',
                    'Parent portal & mobile app',
                    'Teacher payroll & HR module',
                    'Class routine & academic calendar',
                    'Reports & dashboard analytics',
                ],
                'pricing_bn' => [
                    ['name' => 'স্টার্টার', 'price' => '৳ ২,০০০/মাস', 'features' => ['৫০ জন শিক্ষার্থী', 'বেসিক মডিউল', 'ইমেইল সাপোর্ট']],
                    ['name' => 'প্রো', 'price' => '৳ ৪,০০০/মাস', 'features' => ['৫০০ জন শিক্ষার্থী', 'সব মডিউল', 'SMS + অগ্রাধিকার সাপোর্ট']],
                    ['name' => 'এন্টারপ্রাইজ', 'price' => 'কাস্টম', 'features' => ['একাধিক শাখা', 'কাস্টমাইজেশন', 'ডেডিকেটেড সাপোর্ট']],
                ],
                'pricing_en' => [
                    ['name' => 'Starter', 'price' => '৳ 2,000/mo', 'features' => ['50 students', 'Basic modules', 'Email support']],
                    ['name' => 'Pro', 'price' => '৳ 4,000/mo', 'features' => ['500 students', 'All modules', 'SMS + priority support']],
                    ['name' => 'Enterprise', 'price' => 'Custom', 'features' => ['Multiple branches', 'Customization', 'Dedicated support']],
                ],
                'faq_bn' => [
                    ['q' => 'স্কুল ম্যানেজমেন্ট সিস্টেম কি ক্লাউড-ভিত্তিক?', 'a' => 'হ্যাঁ, এটি সম্পূর্ণ ক্লাউড-ভিত্তিক। যেকোনো ডিভাইস থেকে ব্রাউজার দিয়ে লগইন করা যায়।'],
                    ['q' => 'অভিভাবকদের কি আলাদা অ্যাপ দরকার?', 'a' => 'অভিভাবকরা ওয়েব পোর্টাল বা আমাদের মোবাইল অ্যাপ দুটোই ব্যবহার করতে পারবেন।'],
                    ['q' => 'ফি কালেকশন কি অনলাইনে করা যায়?', 'a' => 'হ্যাঁ, বিকাশ/নগদ/কার্ডের মাধ্যমে অনলাইন ফি আদায় এবং SMS রিমাইন্ডার সমর্থিত।'],
                    ['q' => 'ট্রায়াল কত দিনের?', 'a' => 'আমরা ১৪ দিনের ফ্রি ট্রায়াল দিই, কোনো ক্রেডিট কার্ড ছাড়াই।'],
                    ['q' => 'সাবস্ক্রিপশন কীভাবে নেব?', 'a' => 'মাসিক বা বার্ষিক প্ল্যান বেছে নিয়ে সরাসরি নিবন্ধন করে সাবস্ক্রাইব করতে পারবেন।'],
                    ['q' => 'আমাদের ডেটা কি নিরাপদ?', 'a' => 'হ্যাঁ, প্রতিটি স্কুলের ডেটা সম্পূর্ণ আলাদা এবং নিরাপদ সার্ভারে সংরক্ষিত থাকে।'],
                ],
                'faq_en' => [
                    ['q' => 'Is the school management system cloud-based?', 'a' => 'Yes, it is fully cloud-based and accessible from any browser on any device.'],
                    ['q' => 'Do parents need a separate app?', 'a' => 'Parents can use either the web portal or our mobile app.'],
                    ['q' => 'Can fees be collected online?', 'a' => 'Yes, online fee collection via bKash/Nagad/cards and SMS reminders are supported.'],
                    ['q' => 'How long is the trial?', 'a' => 'We offer a 14-day free trial, no credit card required.'],
                    ['q' => 'How do I subscribe?', 'a' => 'Choose a monthly or yearly plan and register directly to subscribe.'],
                    ['q' => 'Is our data secure?', 'a' => 'Yes, each school\'s data is fully isolated and stored on secure servers.'],
                ],
                'demo_url' => 'https://school.regal-solution.com',
                'register_url' => 'https://school.regal-solution.com/register',
                'login_url' => 'https://school.regal-solution.com/login',
                'is_saas' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'slug' => 'apartment-management',
                'name_bn' => 'অ্যাপার্টমেন্ট ম্যানেজমেন্ট',
                'name_en' => 'Apartment Management',
                'tagline_bn' => 'বিল্ডিং ব্যবস্থাপনা এখন সহজ',
                'tagline_en' => 'Building management made easy',
                'summary_bn' => 'মেইনটেন্যান্স বিল, অভিযোগ, ভাড়াটিয়া ও মালিক ব্যবস্থাপনা, এবং মিটিং নোটিশ — সব স্বয়ংক্রিয়।',
                'summary_en' => 'Maintenance bills, complaints, tenant & owner management, and meeting notices — all automated.',
                'features_bn' => [
                    'মেইনটেন্যান্স বিল তৈরি ও কালেকশন',
                    'ভাড়াটিয়া ও মালিক ডাটাবেস',
                    'অভিযোগ ট্র্যাকিং সিস্টেম',
                    'কমিটি ও মিটিং ব্যবস্থাপনা',
                    'SMS ও নোটিশ বোর্ড',
                    'আয়-ব্যয় হিসাব',
                ],
                'features_en' => [
                    'Maintenance bill generation & collection',
                    'Tenant & owner database',
                    'Complaint tracking system',
                    'Committee & meeting management',
                    'SMS & notice board',
                    'Income & expense accounting',
                ],
                'pricing_bn' => [
                    ['name' => 'ট্রায়াল', 'price' => '১৪ দিন ফ্রি', 'features' => ['সব ফিচার আনলক', 'ডেমো ডেটা', 'কোনো কার্ড লাগবে না']],
                    ['name' => 'মাসিক', 'price' => '৳ ৪০–৬০/ফ্ল্যাট', 'features' => ['১–১০ ফ্ল্যাট: ৳৬০', '১১–৩০ ফ্ল্যাট: ৳৫০', '৩১+ ফ্ল্যাট: ৳৪০']],
                    ['name' => '৬ মাস', 'price' => '১০% ছাড়', 'features' => ['মাসিক বিলে ১০% ছাড়', 'সব ফিচার', 'অগ্রাধিকার সাপোর্ট']],
                    ['name' => '১২ মাস (বার্ষিক)', 'price' => '১৫% ছাড়', 'features' => ['প্রায় ২ মাস ফ্রি', 'সেটআপ ফি ফ্রি', 'সর্বোচ্চ সাশ্রয়']],
                    ['name' => 'সেটআপ ফি (এককালীন)', 'price' => '৳ ১,৫০০–২,৫০০', 'features' => ['নিয়মিত: ৳২,৫০০', 'লঞ্চ অফার: ৳১,৫০০', 'বার্ষিক প্ল্যানে: ফ্রি']],
                ],
                'pricing_en' => [
                    ['name' => 'Trial', 'price' => '14 days free', 'features' => ['All features unlocked', 'Demo data', 'No card required']],
                    ['name' => 'Monthly', 'price' => '৳ 40–60/flat', 'features' => ['1–10 flats: ৳60', '11–30 flats: ৳50', '31+ flats: ৳40']],
                    ['name' => '6 months', 'price' => '10% off', 'features' => ['10% off monthly bill', 'All features', 'Priority support']],
                    ['name' => '12 months (yearly)', 'price' => '15% off', 'features' => ['~2 months free', 'Setup fee FREE', 'Best value']],
                    ['name' => 'Setup fee (one-time)', 'price' => '৳ 1,500–2,500', 'features' => ['Regular: ৳2,500', 'Launch offer: ৳1,500', 'Yearly plan: FREE']],
                ],
                'faq_bn' => [
                    ['q' => 'বিল কি অনলাইনে দেওয়া যায়?', 'a' => 'হ্যাঁ, মোবাইল ব্যাংকিং বা কার্ডে অনলাইনে মেইনটেন্যান্স বিল পরিশোধ করা যায়।'],
                    ['q' => 'অভিযোগ কীভাবে ট্র্যাক হয়?', 'a' => 'প্রতিটি অভিযোগের স্ট্যাটাস ও দায়িত্বপ্রাপ্ত ব্যক্তি দেখা যায় এবং সমাধান হলে নোটিফিকেশন যায়।'],
                    ['q' => 'ট্রায়াল কত দিনের?', 'a' => '১৪ দিনের ফ্রি ট্রায়াল, কোনো ক্রেডিট কার্ড ছাড়াই।'],
                    ['q' => 'মূল্য কীভাবে নির্ধারিত হয়?', 'a' => 'ফ্ল্যাট সংখ্যা অনুযায়ী — ১–১০ ফ্ল্যাট ৳৬০, ১১–৩০ ফ্ল্যাট ৳৫০ এবং ৩১+ ফ্ল্যাট ৳৪০ (প্রতি ফ্ল্যাট/মাস)।'],
                    ['q' => 'কমিটি ভিত্তিক বিল্ডিংয়ের আলাদা ব্যবস্থা আছে?', 'a' => 'হ্যাঁ, সভাপতি/সম্পাদক/কোষাধ্যক্ষসহ কমিটি ম্যানেজমেন্ট ও মিটিং নোটিশ সুবিধা আছে।'],
                    ['q' => 'ডেটা কি নিরাপদ?', 'a' => 'হ্যাঁ, প্রতিটি সংস্থার ডেটা সম্পূর্ণ আলাদা (multi-tenant) এবং নিয়মিত ব্যাকআপ নেওয়া হয়।'],
                ],
                'faq_en' => [
                    ['q' => 'Can bills be paid online?', 'a' => 'Yes, maintenance bills can be paid online via mobile banking or card.'],
                    ['q' => 'How are complaints tracked?', 'a' => 'Each complaint shows its status and assignee, and notifications are sent on resolution.'],
                    ['q' => 'How long is the trial?', 'a' => 'A 14-day free trial, no credit card required.'],
                    ['q' => 'How is pricing determined?', 'a' => 'By flat count — 1–10 flats ৳60, 11–30 flats ৳50, and 31+ flats ৳40 (per flat/month).'],
                    ['q' => 'Is there support for committee-based buildings?', 'a' => 'Yes, committee management (president/secretary/treasurer) and meeting notices are included.'],
                    ['q' => 'Is my data secure?', 'a' => 'Yes, each organization\'s data is fully isolated (multi-tenant) and backed up regularly.'],
                ],
                'demo_url' => 'https://apartment.regal-solution.com',
                'register_url' => 'https://apartment.regal-solution.com/register',
                'login_url' => 'https://apartment.regal-solution.com/login',
                'download_url' => 'https://apartment.regal-solution.com',
                'is_saas' => true,
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'slug' => 'sales-crm',
                'name_bn' => 'সেলস CRM',
                'name_en' => 'Sales CRM',
                'tagline_bn' => 'লিড থেকে সেলস — পুরো পাইপলাইন',
                'tagline_en' => 'From lead to sale — the whole pipeline',
                'summary_bn' => 'লিড ক্যাপচার, ফলো-আপ, কোটেশন, ইনভয়েস ও টিম পারফরম্যান্স ট্র্যাকিং এক প্ল্যাটফর্মে।',
                'summary_en' => 'Lead capture, follow-ups, quotations, invoices, and team performance tracking in one platform.',
                'features_bn' => [
                    'লিড ক্যাপচার ও অ্যাসাইনমেন্ট',
                    'ফলো-আপ রিমাইন্ডার (SMS/ইমেইল)',
                    'কোটেশন ও ইনভয়েস তৈরি',
                    'পাইপলাইন ও স্টেজ ম্যানেজমেন্ট',
                    'টিম টার্গেট ও রিপোর্ট',
                    'কল ও অ্যাক্টিভিটি লগ',
                ],
                'features_en' => [
                    'Lead capture & assignment',
                    'Follow-up reminders (SMS/email)',
                    'Quotation & invoice generation',
                    'Pipeline & stage management',
                    'Team targets & reports',
                    'Call & activity logging',
                ],
                'pricing_bn' => [
                    ['name' => 'স্টার্টার', 'price' => '৳ ১,০০০/মাস', 'features' => ['৩ জন ইউজার', 'লিড ও ফলো-আপ', 'বেসিক রিপোর্ট']],
                    ['name' => 'গ্রোথ', 'price' => '৳ ২,৫০০/মাস', 'features' => ['১০ জন ইউজার', 'কোটেশন/ইনভয়েস', 'অগ্রাধিকার সাপোর্ট']],
                ],
                'pricing_en' => [
                    ['name' => 'Starter', 'price' => '৳ 1,000/mo', 'features' => ['3 users', 'Leads & follow-ups', 'Basic reports']],
                    ['name' => 'Growth', 'price' => '৳ 2,500/mo', 'features' => ['10 users', 'Quotes/invoices', 'Priority support']],
                ],
                'faq_bn' => [
                    ['q' => 'লিড কোথা থেকে আসতে পারে?', 'a' => 'ওয়েবসাইট ফর্ম, ম্যানুয়াল এন্ট্রি, কল ও ইমেইল থেকে লিড সংগ্রহ করা যায়।'],
                    ['q' => 'SMS পাঠানো যায়?', 'a' => 'হ্যাঁ, bulksmsbd গেটওয়ে ব্যবহার করে গ্রাহককে SMS পাঠানো যায়।'],
                    ['q' => 'টিম মেম্বার যোগ করা যায়?', 'a' => 'হ্যাঁ, প্ল্যান অনুযায়ী একাধিক ইউজার যোগ করে রোল ও পারমিশন দেওয়া যায়।'],
                    ['q' => 'রিপোর্ট কি রিয়েল-টাইম?', 'a' => 'হ্যাঁ, লিড, সেলস ও টিম পারফরম্যান্সের রিয়েল-টাইম ড্যাশবোর্ড থাকে।'],
                ],
                'faq_en' => [
                    ['q' => 'Where can leads come from?', 'a' => 'Leads can be captured from website forms, manual entry, calls, and email.'],
                    ['q' => 'Can SMS be sent?', 'a' => 'Yes, SMS can be sent to customers using the bulksmsbd gateway.'],
                    ['q' => 'Can I add team members?', 'a' => 'Yes, you can add multiple users with roles and permissions depending on your plan.'],
                    ['q' => 'Are reports real-time?', 'a' => 'Yes, there is a real-time dashboard for leads, sales, and team performance.'],
                ],
                'demo_url' => 'https://crm.regal-solution.com',
                'register_url' => 'https://crm.regal-solution.com/register',
                'login_url' => 'https://crm.regal-solution.com/login',
                'is_saas' => true,
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'slug' => 'mosque-management',
                'name_bn' => 'মসজিদ ম্যানেজমেন্ট',
                'name_en' => 'Mosque Management',
                'tagline_bn' => 'মসজিদের দান ও হিসাব স্বচ্ছ রাখুন',
                'tagline_en' => 'Keep your mosque\'s donations & accounts transparent',
                'summary_bn' => 'দান সংগ্রহ, খরচ হিসাব, কমিটি ও মাদ্রাসা শিক্ষার্থী ব্যবস্থাপনা।',
                'summary_en' => 'Donation collection, expense accounting, committee, and madrasa student management.',
                'features_bn' => [
                    'দান ও চাঁদা সংগ্রহ',
                    'আয়-ব্যয় লেজার',
                    'কমিটি ব্যবস্থাপনা',
                    'মাদ্রাসা শিক্ষার্থী তালিকা',
                    'SMS নোটিশ',
                    'স্বচ্ছ রিপোর্ট',
                ],
                'features_en' => [
                    'Donation & subscription collection',
                    'Income-expense ledger',
                    'Committee management',
                    'Madrasa student roster',
                    'SMS notices',
                    'Transparent reports',
                ],
                'pricing_bn' => [
                    ['name' => 'স্ট্যান্ডার্ড', 'price' => '৳ ১,০০০/মাস', 'features' => ['দান ও হিসাব', 'কমিটি', 'SMS নোটিশ']],
                ],
                'pricing_en' => [
                    ['name' => 'Standard', 'price' => '৳ 1,000/mo', 'features' => ['Donations & accounts', 'Committee', 'SMS notices']],
                ],
                'faq_bn' => [
                    ['q' => 'দান কি অনলাইনে নেওয়া যায়?', 'a' => 'হ্যাঁ, মোবাইল ব্যাংকিং/কার্ডে অনলাইন দান নেওয়া যায়।'],
                    ['q' => 'রিপোর্ট কি সবার জন্য উন্মুক্ত?', 'a' => 'কমিটির সিদ্ধান্ত অনুযায়ী নির্দিষ্ট রিপোর্ট পাবলিক বা প্রাইভেট রাখা যায়।'],
                    ['q' => 'মাদ্রাসা শিক্ষার্থী ব্যবস্থাপনা আছে?', 'a' => 'হ্যাঁ, শিক্ষার্থী তালিকা ও উপস্থিতি ব্যবস্থাপনা করা যায়।'],
                    ['q' => 'রিপোর্ট কি মুদ্রণযোগ্য?', 'a' => 'হ্যাঁ, মাসিক আয়-ব্যয় রিপোর্ট PDF বা প্রিন্ট করা যায়।'],
                ],
                'faq_en' => [
                    ['q' => 'Can donations be collected online?', 'a' => 'Yes, online donations can be collected via mobile banking/card.'],
                    ['q' => 'Are reports public?', 'a' => 'Per committee decision, specific reports can be kept public or private.'],
                    ['q' => 'Is madrasa student management included?', 'a' => 'Yes, student rosters and attendance can be managed.'],
                    ['q' => 'Are reports printable?', 'a' => 'Yes, monthly income-expense reports can be exported as PDF or printed.'],
                ],
                'demo_url' => null,
                'register_url' => null,
                'login_url' => null,
                'is_saas' => true,
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'slug' => 'pos',
                'name_bn' => 'POS সফটওয়্যার',
                'name_en' => 'POS Software',
                'tagline_bn' => 'দ্রুত বিলিং, সহজ ইনভেন্টরি',
                'tagline_en' => 'Fast billing, simple inventory',
                'summary_bn' => 'দোকান ও রেস্তোরাঁর জন্য বারকোড বিলিং, ইনভেন্টরি ও সেলস রিপোর্ট।',
                'summary_en' => 'Barcode billing, inventory, and sales reports for shops and restaurants.',
                'features_bn' => [
                    'বারকোড বিলিং ও রসিদ প্রিন্টিং',
                    'ইনভেন্টরি ট্র্যাকিং ও লো-স্টক অ্যালার্ট',
                    'দৈনিক সেলস ড্যাশবোর্ড',
                    'ক্যাশিয়ার ও মাল্টি-ইউজার রোল',
                    'কাস্টম রসিদ',
                    'অফলাইন মোড',
                ],
                'features_en' => [
                    'Barcode billing & receipt printing',
                    'Inventory tracking with low-stock alerts',
                    'Daily sales dashboard',
                    'Cashier & multi-user roles',
                    'Custom receipts',
                    'Offline mode',
                ],
                'pricing_bn' => [
                    ['name' => 'স্ট্যান্ডার্ড', 'price' => '৳ ১,২০০/মাস', 'features' => ['১টি আউটলেট', 'বিলিং ও ইনভেন্টরি', 'বেসিক রিপোর্ট']],
                    ['name' => 'মাল্টি-আউটলেট', 'price' => '৳ ২,৫০০/মাস', 'features' => ['একাধিক আউটলেট', 'সেন্ট্রাল ইনভেন্টরি', 'অগ্রাধিকার সাপোর্ট']],
                ],
                'pricing_en' => [
                    ['name' => 'Standard', 'price' => '৳ 1,200/mo', 'features' => ['1 outlet', 'Billing & inventory', 'Basic reports']],
                    ['name' => 'Multi-outlet', 'price' => '৳ 2,500/mo', 'features' => ['Multiple outlets', 'Central inventory', 'Priority support']],
                ],
                'faq_bn' => [
                    ['q' => 'ইন্টারনেট না থাকলে কাজ হবে?', 'a' => 'হ্যাঁ, অফলাইন মোডে বিলিং চলে এবং সংযোগ ফিরলে ডেটা সিঙ্ক হয়।'],
                    ['q' => 'কোন প্রিন্টার লাগবে?', 'a' => 'থার্মাল প্রিন্টার ও A4 প্রিন্টার দুটোই সমর্থিত।'],
                    ['q' => 'বারকোড স্ক্যানার লাগবে?', 'a' => 'হ্যাঁ, যেকোনো USB বারকোড স্ক্যানার সহজেই সংযোগ করা যায়।'],
                    ['q' => 'একাধিক শাখা চালানো যায়?', 'a' => 'হ্যাঁ, মাল্টি-আউটলেট প্ল্যানে একাধিক শাখার সেন্ট্রাল ইনভেন্টরি চলে।'],
                ],
                'faq_en' => [
                    ['q' => 'Does it work without internet?', 'a' => 'Yes, billing works in offline mode and data syncs when connection returns.'],
                    ['q' => 'Which printers are supported?', 'a' => 'Both thermal and A4 printers are supported.'],
                    ['q' => 'Do I need a barcode scanner?', 'a' => 'Yes, any USB barcode scanner can be connected easily.'],
                    ['q' => 'Can I run multiple outlets?', 'a' => 'Yes, the multi-outlet plan supports central inventory across multiple branches.'],
                ],
                'demo_url' => null,
                'register_url' => null,
                'login_url' => null,
                'is_saas' => true,
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'slug' => 'bus-ticket',
                'name_bn' => 'বাস টিকেট বুকিং',
                'name_en' => 'Bus Ticket Booking',
                'tagline_bn' => 'সিট ম্যাপ, কাউন্টার ও ফ্লিট ম্যানেজমেন্ট',
                'tagline_en' => 'Seat maps, counters & fleet management',
                'summary_bn' => 'অনলাইন বুকিং, সিট ম্যাপ, কাউন্টার নেটওয়ার্ক ও দৈনিক হিসাব।',
                'summary_en' => 'Online booking, seat maps, counter networks, and daily closing.',
                'features_bn' => [
                    'সিট-ভিত্তিক বুকিং ও QR ই-টিকেট',
                    'রুট ও ট্রিপ ব্যবস্থাপনা',
                    'মাল্টি-কাউন্টার নেটওয়ার্ক',
                    'ফ্লিট ও ড্রাইভার রোস্টার',
                    'দৈনিক আর্থিক সমাপ্তি',
                    'রাজস্ব রিপোর্ট ও অ্যানালিটিক্স',
                ],
                'features_en' => [
                    'Seat-wise booking & QR e-tickets',
                    'Route & trip management',
                    'Multi-counter network',
                    'Fleet & driver roster',
                    'Daily financial closing',
                    'Revenue reports & analytics',
                ],
                'pricing_bn' => [
                    ['name' => 'স্ট্যান্ডার্ড', 'price' => '৳ ২,০০০/মাস', 'features' => ['১০টি বাস', 'বুকিং ও কাউন্টার', 'বেসিক রিপোর্ট']],
                    ['name' => 'এন্টারপ্রাইজ', 'price' => 'কাস্টম', 'features' => ['আনলিমিটেড ফ্লিট', 'সব ফিচার', 'ডেডিকেটেড সাপোর্ট']],
                ],
                'pricing_en' => [
                    ['name' => 'Standard', 'price' => '৳ 2,000/mo', 'features' => ['10 buses', 'Booking & counters', 'Basic reports']],
                    ['name' => 'Enterprise', 'price' => 'Custom', 'features' => ['Unlimited fleet', 'All features', 'Dedicated support']],
                ],
                'faq_bn' => [
                    ['q' => 'যাত্রী কি অনলাইনে টিকেট কাটতে পারবেন?', 'a' => 'হ্যাঁ, যাত্রী ওয়েব বা অ্যাপে সিট বেছে নিয়ে অনলাইনে টিকেট কিনতে পারবেন।'],
                    ['q' => 'QR টিকেট কীভাবে কাজ করে?', 'a' => 'প্রতিটি বুকিংয়ে ইউনিক QR কোড তৈরি হয়, বোর্ডিং স্টাফ স্ক্যান করে যাচাই করে।'],
                    ['q' => 'মোবাইলে ব্যবহার করা যায়?', 'a' => 'হ্যাঁ, সম্পূর্ণ রেসপনসিভ — ফোন বা ট্যাবলেট থেকে কাউন্টার চালানো যায়।'],
                    ['q' => 'কী কী রিপোর্ট পাওয়া যায়?', 'a' => 'দৈনিক সমাপ্তি, রুট, রাজস্ব ও অ্যানালিটিক্স রিপোর্ট পাওয়া যায়।'],
                ],
                'faq_en' => [
                    ['q' => 'Can passengers book online?', 'a' => 'Yes, passengers can choose seats and buy tickets online via web or app.'],
                    ['q' => 'How does QR ticketing work?', 'a' => 'Each booking gets a unique QR code that boarding staff scan for verification.'],
                    ['q' => 'Can it be used on mobile?', 'a' => 'Yes, it is fully responsive — counters work on phones and tablets.'],
                    ['q' => 'What reports are available?', 'a' => 'Daily closing, route, revenue, and analytics reports are available.'],
                ],
                'demo_url' => 'https://bus.regal-solution.com',
                'register_url' => 'https://bus.regal-solution.com/register',
                'login_url' => 'https://bus.regal-solution.com/login',
                'is_saas' => true,
                'sort_order' => 6,
                'is_active' => true,
            ],
            [
                'slug' => 'ecommerce-website',
                'name_bn' => 'ই-কমার্স ওয়েবসাইট',
                'name_en' => 'E-commerce Website',
                'tagline_bn' => 'আপনার ব্যবসার জন্য সম্পূর্ণ অনলাইন স্টোর',
                'tagline_en' => 'A complete online store for your business',
                'summary_bn' => 'কাস্টম ডিজাইনের ই-কমার্স সাইট — প্রোডাক্ট, কার্ট, পেমেন্ট ও অর্ডার ম্যানেজমেন্টসহ।',
                'summary_en' => 'Custom-designed e-commerce site with products, cart, payments, and order management.',
                'features_bn' => [
                    'কাস্টম রেসপনসিভ ডিজাইন',
                    'প্রোডাক্ট ক্যাটালগ ও ক্যাটাগরি',
                    'কার্ট ও চেকআউট',
                    'বিকাশ/নগদ/কার্ড পেমেন্ট',
                    'অর্ডার ম্যানেজমেন্ট',
                    'SEO অপটিমাইজড',
                ],
                'features_en' => [
                    'Custom responsive design',
                    'Product catalog & categories',
                    'Cart & checkout',
                    'bKash/Nagad/card payments',
                    'Order management',
                    'SEO optimized',
                ],
                'pricing_bn' => null,
                'pricing_en' => null,
                'faq_bn' => [
                    ['q' => 'কত সময়ে ওয়েবসাইট তৈরি হবে?', 'a' => 'সাধারণত ২-৪ সপ্তাহে সম্পূর্ণ সাইট ডেলিভারি করা হয়, চাহিদার উপর নির্ভর করে।'],
                    ['q' => 'পেমেন্ট গেটওয়ে যুক্ত করা যায়?', 'a' => 'হ্যাঁ, বিকাশ, নগদ ও কার্ড পেমেন্ট ইন্টিগ্রেশন করা হয়।'],
                    ['q' => 'কন্টেন্ট কি নিজেই আপডেট করতে পারব?', 'a' => 'হ্যাঁ, অ্যাডমিন প্যানেল থেকে প্রোডাক্ট ও কন্টেন্ট নিজেই ম্যানেজ করতে পারবেন।'],
                    ['q' => 'হোস্টিং ও ডোমেইন কে দেবে?', 'a' => 'আমরা ডোমেইন ও হোস্টিং সেটআপে সম্পূর্ণ সহায়তা করি।'],
                ],
                'faq_en' => [
                    ['q' => 'How long does it take?', 'a' => 'Typically 2-4 weeks depending on requirements.'],
                    ['q' => 'Can payment gateways be integrated?', 'a' => 'Yes, bKash, Nagad, and card payment integrations are available.'],
                    ['q' => 'Can I update content myself?', 'a' => 'Yes, you can manage products and content yourself from the admin panel.'],
                    ['q' => 'Who provides hosting and domain?', 'a' => 'We fully assist with domain and hosting setup.'],
                ],
                'demo_url' => null,
                'register_url' => null,
                'login_url' => null,
                'is_saas' => false,
                'sort_order' => 7,
                'is_active' => true,
            ],
            [
                'slug' => 'custom-software',
                'name_bn' => 'কাস্টম সফটওয়্যার',
                'name_en' => 'Custom Software',
                'tagline_bn' => 'আপনার চাহিদা অনুযায়ী সফটওয়্যার',
                'tagline_en' => 'Software built to your exact needs',
                'summary_bn' => 'আপনার ব্যবসার নির্দিষ্ট সমস্যার জন্য কাস্টম ওয়েব/মোবাইল সফটওয়্যার ডেভেলপমেন্ট।',
                'summary_en' => 'Custom web/mobile software development for your business\'s specific problems.',
                'features_bn' => [
                    'রিকোয়ারমেন্ট অ্যানালাইসিস',
                    'কাস্টম ওয়েব ও মোবাইল অ্যাপ',
                    'API ইন্টিগ্রেশন',
                    'রিপোর্টিং ও ড্যাশবোর্ড',
                    'ট্রেনিং ও সাপোর্ট',
                    'আপডেট ও মেইনটেন্যান্স',
                ],
                'features_en' => [
                    'Requirement analysis',
                    'Custom web & mobile apps',
                    'API integration',
                    'Reporting & dashboards',
                    'Training & support',
                    'Updates & maintenance',
                ],
                'pricing_bn' => null,
                'pricing_en' => null,
                'faq_bn' => [
                    ['q' => 'কত খরচ হবে?', 'a' => 'রিকোয়ারমেন্ট অনুযায়ী খরচ নির্ধারিত হয়। প্রথমে ফ্রি কনসালটেশন নিন।'],
                    ['q' => 'সাপোর্ট কি দেওয়া হয়?', 'a' => 'হ্যাঁ, ডেলিভারির পর ট্রেনিং ও মেইনটেন্যান্স সাপোর্ট দেওয়া হয়।'],
                    ['q' => 'ডেভেলপমেন্টে কত সময় লাগে?', 'a' => 'প্রজেক্টের স্কেল অনুযায়ী সাধারণত ২–৮ সপ্তাহ লাগে।'],
                    ['q' => 'সোর্স কোড কি আমি পাব?', 'a' => 'চুক্তি অনুযায়ী সোর্স কোড ও ডকুমেন্টেশন ডেলিভারি করা হয়।'],
                ],
                'faq_en' => [
                    ['q' => 'How much does it cost?', 'a' => 'Cost depends on requirements. Get a free consultation first.'],
                    ['q' => 'Is support provided?', 'a' => 'Yes, training and maintenance support are provided after delivery.'],
                    ['q' => 'How long does development take?', 'a' => 'Typically 2–8 weeks depending on project scope.'],
                    ['q' => 'Will I get the source code?', 'a' => 'Source code and documentation are delivered per the agreement.'],
                ],
                'demo_url' => null,
                'register_url' => null,
                'login_url' => null,
                'is_saas' => false,
                'sort_order' => 8,
                'is_active' => true,
            ],
        ];

        foreach ($products as $data) {
            Product::query()->updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
