<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'slug' => 'school-management',
                'name_bn' => 'স্কুল ম্যানেজমেন্ট সিস্টেম',
                'name_en' => 'School Management System',
                'tagline_bn' => 'স্কুলের সব কাজ এক প্ল্যাটফর্মে',
                'tagline_en' => 'Run your entire school from one platform',
                'summary_bn' => 'ভর্তি, উপস্থিতি, পরীক্ষার ফলাফল, ফি ও শিক্ষার্থী-অভিভাবক যোগাযোগ — সবকিছু এক জায়গায়, স্বয়ংক্রিয়ভাবে।',
                'summary_en' => 'Admissions, attendance, results, fees, and parent communication — all in one place, automated.',
                'features_bn' => [
                    ['t' => 'অনলাইন ভর্তি ও শিক্ষার্থী প্রোফাইল', 'd' => 'কাগজের ফরম আর খাতার তালিকা নয় — অনলাইন আবেদন, অনুমোদন, আর প্রতিটি শিক্ষার্থীর ছবি, অভিভাবক ও ডকুমেন্ট এক জায়গায়।'],
                    ['t' => 'দৈনিক উপস্থিতি (ম্যানুয়াল ও বায়োমেট্রিক)', 'd' => 'এক ক্লিকে উপস্থিতি নিন; অনুপস্থিত শিক্ষার্থীর অভিভাবককে সঙ্গে সঙ্গে SMS যায় — ক্লাসের উপস্থিতি আর নিয়ন্ত্রণের বাইরে থাকবে না।'],
                    ['t' => 'পরীক্ষা ও রেজাল্ট কার্ড', 'd' => 'পরীক্ষার রুটিন, মার্কস এন্ট্রি, গ্রেড ও রেজাল্ট কার্ড অটো-জেনারেট হয়; রেজাল্ট অভিভাবককে SMS-এও পাঠাতে পারবেন।'],
                    ['t' => 'ফি সংগ্রহ ও ডিউ রিমাইন্ডার', 'd' => 'বিকাশ/নগদ/কার্ডে অনলাইন ফি, অটো রসিদ, আর বাকি পড়লে অভিভাবককে স্বয়ংক্রিয় SMS — ফি আদায় বাড়বে, ঝামেলা কমবে।'],
                    ['t' => 'অভিভাবক পোর্টাল ও মোবাইল অ্যাপ', 'd' => 'অভিভাবক ফোন থেকেই সন্তানের উপস্থিতি, রেজাল্ট, হোমওয়ার্ক ও নোটিশ দেখতে পারবেন — বারবার স্কুলে ফোন করার দরকার নেই।'],
                    ['t' => 'শিক্ষক ও HR মডিউল', 'd' => 'শিক্ষক প্রোফাইল, বেতন, ছুটি ও উপস্থিতি ট্র্যাকিং — বেতন হিসাবে আর ভুল হবে না।'],
                    ['t' => 'ক্লাস রুটিন ও একাডেমিক ক্যালেন্ডার', 'd' => 'রুটিন, পরীক্ষার সময়সূচি, ইভেন্ট ও ছুটির দিন — সব এক ক্যালেন্ডারে, কোনো কনফিউশন নেই।'],
                    ['t' => 'SMS ও নোটিশ বোর্ড', 'd' => 'অভিভাবক ও শিক্ষার্থীকে গণবিজ্ঞপ্তি, ইভেন্ট রিমাইন্ডার আর জরুরি খবর এক ক্লিকে পাঠান।'],
                    ['t' => 'রিপোর্ট ও ড্যাশবোর্ড অ্যানালিটিক্স', 'd' => 'ভর্তি, ফি আদায়, উপস্থিতি ও রেজাল্টের রিয়েল-টাইম চিত্র — সিদ্ধান্ত নিন ডেটা দেখে, অনুমানে নয়।'],
                ],
                'features_en' => [
                    ['t' => 'Online admission & student profiles', 'd' => 'No more paper forms and ledgers — online applications, approvals, and each student\'s photo, guardian, and documents in one place.'],
                    ['t' => 'Daily attendance (manual & biometric)', 'd' => 'Take attendance in one click; an SMS goes to the guardian instantly when a student is absent — attendance stays under control.'],
                    ['t' => 'Exams & report cards', 'd' => 'Exam schedules, marks entry, grades, and auto-generated report cards; results can also be sent to parents by SMS.'],
                    ['t' => 'Fee collection & due reminders', 'd' => 'Online fees via bKash/Nagad/card, auto receipts, and automatic SMS when dues remain — higher collection, less hassle.'],
                    ['t' => 'Parent portal & mobile app', 'd' => 'Parents see attendance, results, homework, and notices right from their phone — no more repeated calls to the school.'],
                    ['t' => 'Teacher & HR module', 'd' => 'Teacher profiles, payroll, leave, and attendance tracking — no more mistakes in salary calculation.'],
                    ['t' => 'Class routine & academic calendar', 'd' => 'Routines, exam schedules, events, and holidays — all in one calendar, zero confusion.'],
                    ['t' => 'SMS & notice board', 'd' => 'Send bulk notices, event reminders, and urgent news to parents and students in one click.'],
                    ['t' => 'Reports & dashboard analytics', 'd' => 'Real-time view of admissions, fee collection, attendance, and results — decide with data, not guesswork.'],
                ],
                'pricing_bn' => null,
                'pricing_en' => null,
                'faq_bn' => [
                    ['q' => 'স্কুল ম্যানেজমেন্ট সিস্টেম কি ক্লাউড-ভিত্তিক?', 'a' => 'হ্যাঁ, সম্পূর্ণ ক্লাউড-ভিত্তিক। যেকোনো ডিভাইসের ব্রাউজার থেকে লগইন করে ব্যবহার করা যায়, আলাদা সার্ভার লাগে না।'],
                    ['q' => 'অভিভাবকদের কি আলাদা অ্যাপ দরকার?', 'a' => 'না। অভিভাবকরা ওয়েব পোর্টাল বা আমাদের মোবাইল অ্যাপ — যেকোনো একটি ব্যবহার করলেই হবে, দুটোই একই ডেটা দেখায়।'],
                    ['q' => 'ফি কি অনলাইনে নেওয়া যায়?', 'a' => 'হ্যাঁ, বিকাশ/নগদ/কার্ডে অনলাইন ফি আদায় হয়, রসিদ অটো তৈরি হয়, আর বকেয়া থাকলে অভিভাবককে SMS রিমাইন্ডার যায়।'],
                    ['q' => 'আগের খাতার ডেটা কি এখানে আনা যাবে?', 'a' => 'হ্যাঁ, আমাদের টিম Excel/পেপার থেকে শিক্ষার্থী, শিক্ষক ও ফি-র পুরনো ডেটা ইমপোর্ট করে দেয়, কোনো তথ্য হারায় না।'],
                    ['q' => 'ট্রায়াল কত দিনের?', 'a' => '১৪ দিনের সম্পূর্ণ ফ্রি ট্রায়াল — কোনো ক্রেডিট কার্ড লাগে না, সব ফিচার খুলে দেওয়া হয়।'],
                    ['q' => 'একাধিক শাখা চালানো যাবে?', 'a' => 'হ্যাঁ, এন্টারপ্রাইজ প্ল্যানে একাধিক শাখার কেন্দ্রীয় নিয়ন্ত্রণ এবং প্রতিটি শাখার আলাদা রিপোর্ট পাওয়া যায়।'],
                    ['q' => 'আমাদের ডেটা কি নিরাপদ?', 'a' => 'হ্যাঁ, প্রতিটি স্কুলের ডেটা সম্পূর্ণ আলাদা (multi-tenant), এনক্রিপ্টেড এবং নিয়মিত ব্যাকআপ নেওয়া হয়।'],
                    ['q' => 'ট্রেনিং ও সাপোর্ট কি দেওয়া হয়?', 'a' => 'হ্যাঁ, চালুর সময় প্রশিক্ষণ দেওয়া হয় এবং পরে ফোন/WhatsApp-এ সাপোর্ট পাওয়া যায় — বাংলায়।'],
                    ['q' => 'সাবস্ক্রিপশন কীভাবে নেব?', 'a' => 'আমাদের টিমের সাথে কথা বলুন; আপনার স্কুলের আকার বুঝে সঠিক প্ল্যান ঠিক করে কলব্যাক দেব — কোনো চাপ নেই।'],
                ],
                'faq_en' => [
                    ['q' => 'Is the school management system cloud-based?', 'a' => 'Yes, fully cloud-based. Log in from any device\'s browser — no separate server required.'],
                    ['q' => 'Do parents need a separate app?', 'a' => 'No. Parents can use either the web portal or our mobile app — both show the same data.'],
                    ['q' => 'Can fees be collected online?', 'a' => 'Yes, fees are collected online via bKash/Nagad/card, receipts are auto-generated, and SMS reminders go out when dues remain.'],
                    ['q' => 'Can old paper records be imported?', 'a' => 'Yes, our team imports existing student, teacher, and fee data from Excel or paper — nothing is lost.'],
                    ['q' => 'How long is the trial?', 'a' => 'A full 14-day free trial — no credit card required, all features unlocked.'],
                    ['q' => 'Can multiple branches be run?', 'a' => 'Yes, the Enterprise plan offers central control of multiple branches with separate reports per branch.'],
                    ['q' => 'Is our data secure?', 'a' => 'Yes, each school\'s data is fully isolated (multi-tenant), encrypted, and backed up regularly.'],
                    ['q' => 'Is training and support provided?', 'a' => 'Yes, onboarding training is provided, plus ongoing phone/WhatsApp support in Bangla.'],
                    ['q' => 'How do I subscribe?', 'a' => 'Talk to our team — we\'ll find the right plan for your school size and call you back. No pressure.'],
                ],
                'demo_url' => 'https://school.regal-solution.com',
                'register_url' => 'https://school.regal-solution.com/register',
                'login_url' => 'https://school.regal-solution.com/login',
                'is_saas' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'slug' => 'apartment-management',
                'name_bn' => 'অ্যাপার্টমেন্ট ম্যানেজমেন্ট',
                'name_en' => 'Apartment Management',
                'tagline_bn' => 'বিল্ডিং ব্যবস্থাপনা এখন সহজ',
                'tagline_en' => 'Building management made easy',
                'summary_bn' => 'মেইনটেন্যান্স বিল, অভিযোগ, ভাড়াটিয়া ও মালিক ব্যবস্থাপনা, এবং মিটিং নোটিশ — সব স্বয়ংক্রিয়।',
                'summary_en' => 'Maintenance bills, complaints, tenant & owner management, and meeting notices — all automated.',
                'features_bn' => [
                    ['t' => 'মেইনটেন্যান্স বিল তৈরি ও কালেকশন', 'd' => 'প্রতি ফ্ল্যাটের বিল অটো তৈরি হয়, মোবাইল ব্যাংকিং/কার্ডে কালেক্ট হয়, আর বকেয়া থাকলে রিমাইন্ডার যায়।'],
                    ['t' => 'ভাড়াটিয়া ও মালিক ডাটাবেস', 'd' => 'প্রতিটি ফ্ল্যাটে কে থাকেন, কে মালিক — সব তথ্য এক জায়গায়, খোঁজাখুঁজির দরকার নেই।'],
                    ['t' => 'অভিযোগ ট্র্যাকিং সিস্টেম', 'd' => 'লিফট, পানি বা অন্য সমস্যার অভিযোগ দিন, দায়িত্বপ্রাপ্তকে অ্যাসাইন করুন, আর স্ট্যাটাস ট্র্যাক করুন।'],
                    ['t' => 'কমিটি ও মিটিং ব্যবস্থাপনা', 'd' => 'সভাপতি/সম্পাদক/কোষাধ্যক্ষের দায়িত্ব, মিটিং নোটিশ ও সিদ্ধান্ত — সব ডিজিটাল।'],
                    ['t' => 'SMS ও নোটিশ বোর্ড', 'd' => 'জরুরি নোটিশ, মিটিং রিমাইন্ডার বা বিলের খবর — এক ক্লিকে সব ফ্ল্যাটে।'],
                    ['t' => 'আয়-ব্যয় হিসাব', 'd' => 'বিল্ডিংয়ের আয়-ব্যয় স্বচ্ছ লেজারে; মাসিক রিপোর্ট PDF-এ প্রিন্ট/শেয়ার করুন।'],
                ],
                'features_en' => [
                    ['t' => 'Maintenance bill generation & collection', 'd' => 'Per-flat bills are generated automatically, collected via mobile banking/card, and reminders go out for dues.'],
                    ['t' => 'Tenant & owner database', 'd' => 'Who lives in which flat and who owns it — all in one place, no more searching.'],
                    ['t' => 'Complaint tracking system', 'd' => 'File lift, water, or other complaints, assign them, and track status to resolution.'],
                    ['t' => 'Committee & meeting management', 'd' => 'President/secretary/treasurer roles, meeting notices, and decisions — all digital.'],
                    ['t' => 'SMS & notice board', 'd' => 'Urgent notices, meeting reminders, or bill alerts — to every flat in one click.'],
                    ['t' => 'Income & expense accounting', 'd' => 'Transparent building ledger; export monthly reports as PDF to print or share.'],
                ],
                'pricing_bn' => [
                    ['name' => 'ট্রায়াল', 'price' => '১৪ দিন ফ্রি', 'features' => ['সব ফিচার আনলক', 'ডেমো ডেটা', 'কোনো কার্ড লাগবে না']],
                    ['name' => 'মাসিক', 'price' => '৳ ৪০–৬০/ফ্ল্যাট', 'features' => ['১–১০ ফ্ল্যাট: ৳৬০', '১১–৩০ ফ্ল্যাট: ৳৫০', '৩১+ ফ্ল্যাট: ৳৪০']],
                    ['name' => '৬ মাস', 'price' => '১০% ছাড়', 'features' => ['মাসিক বিলে ১০% ছাড়', 'সব ফিচার', 'অগ্রাধিকার সাপোর্ট']],
                    ['name' => '১২ মাস (বার্ষিক)', 'price' => '১৫% ছাড়', 'features' => ['প্রায় ২ মাস ফ্রি', 'সেটআপ ফি ফ্রি', 'সর্বোচ্চ সাশ্রয়']],
                    ['name' => 'সেটআপ ফি (এককালীন)', 'price' => '৳ ১,৫০০–২,৫০০', 'features' => ['নিয়মিত: ৳২,৫০০', 'লঞ্চ অফার: ৳১,৫০০', 'বার্ষিক প্ল্যানে: ফ্রি']],
                ],
                'pricing_en' => [
                    ['name' => 'Trial', 'price' => '14 days free', 'features' => ['All features unlocked', 'Demo data', 'No card required']],
                    ['name' => 'Monthly', 'price' => '৳ 40–60/flat', 'features' => ['1–10 flats: ৳60', '11–30 flats: ৳50', '31+ flats: ৳40']],
                    ['name' => '6 months', 'price' => '10% off', 'features' => ['10% off monthly bill', 'All features', 'Priority support']],
                    ['name' => '12 months (yearly)', 'price' => '15% off', 'features' => ['~2 months free', 'Setup fee FREE', 'Best value']],
                    ['name' => 'Setup fee (one-time)', 'price' => '৳ 1,500–2,500', 'features' => ['Regular: ৳2,500', 'Launch offer: ৳1,500', 'Yearly plan: FREE']],
                ],
                'faq_bn' => [
                    ['q' => 'বিল কি অনলাইনে দেওয়া যায়?', 'a' => 'হ্যাঁ, মোবাইল ব্যাংকিং বা কার্ডে অনলাইনে মেইনটেন্যান্স বিল পরিশোধ করা যায়।'],
                    ['q' => 'অভিযোগ কীভাবে ট্র্যাক হয়?', 'a' => 'প্রতিটি অভিযোগের স্ট্যাটাস ও দায়িত্বপ্রাপ্ত ব্যক্তি দেখা যায় এবং সমাধান হলে নোটিফিকেশন যায়।'],
                    ['q' => 'ট্রায়াল কত দিনের?', 'a' => '১৪ দিনের ফ্রি ট্রায়াল, কোনো ক্রেডিট কার্ড ছাড়াই।'],
                    ['q' => 'মূল্য কীভাবে নির্ধারিত হয়?', 'a' => 'ফ্ল্যাট সংখ্যা অনুযায়ী — ১–১০ ফ্ল্যাট ৳৬০, ১১–৩০ ফ্ল্যাট ৳৫০ এবং ৩১+ ফ্ল্যাট ৳৪০ (প্রতি ফ্ল্যাট/মাস)।'],
                    ['q' => 'কমিটি ভিত্তিক বিল্ডিংয়ের আলাদা ব্যবস্থা আছে?', 'a' => 'হ্যাঁ, সভাপতি/সম্পাদক/কোষাধ্যক্ষসহ কমিটি ম্যানেজমেন্ট ও মিটিং নোটিশ সুবিধা আছে।'],
                    ['q' => 'ডেটা কি নিরাপদ?', 'a' => 'হ্যাঁ, প্রতিটি সংস্থার ডেটা সম্পূর্ণ আলাদা (multi-tenant) এবং নিয়মিত ব্যাকআপ নেওয়া হয়।'],
                ],
                'faq_en' => [
                    ['q' => 'Can bills be paid online?', 'a' => 'Yes, maintenance bills can be paid online via mobile banking or card.'],
                    ['q' => 'How are complaints tracked?', 'a' => 'Each complaint shows its status and assignee, and notifications are sent on resolution.'],
                    ['q' => 'How long is the trial?', 'a' => 'A 14-day free trial, no credit card required.'],
                    ['q' => 'How is pricing determined?', 'a' => 'By flat count — 1–10 flats ৳60, 11–30 flats ৳50, and 31+ flats ৳40 (per flat/month).'],
                    ['q' => 'Is there support for committee-based buildings?', 'a' => 'Yes, committee management (president/secretary/treasurer) and meeting notices are included.'],
                    ['q' => 'Is my data secure?', 'a' => 'Yes, each organization\'s data is fully isolated (multi-tenant) and backed up regularly.'],
                ],
                'demo_url' => 'https://apartment.regal-solution.com',
                'register_url' => 'https://apartment.regal-solution.com/register',
                'login_url' => 'https://apartment.regal-solution.com/login',
                'download_url' => 'https://apartment.regal-solution.com',
                'is_saas' => true,
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'slug' => 'sales-crm',
                'name_bn' => 'সেলস CRM',
                'name_en' => 'Sales CRM',
                'tagline_bn' => 'লিড থেকে সেলস — পুরো পাইপলাইন',
                'tagline_en' => 'From lead to sale — the whole pipeline',
                'summary_bn' => 'লিড ক্যাপচার, ফলো-আপ, কোটেশন, ইনভয়েস ও টিম পারফরম্যান্স ট্র্যাকিং — সব এক প্ল্যাটফর্মে।',
                'summary_en' => 'Lead capture, follow-ups, quotations, invoices, and team performance tracking — all in one platform.',
                'features_bn' => [
                    ['t' => 'লিড ক্যাপচার ও অ্যাসাইনমেন্ট', 'd' => 'ওয়েবসাইট ফর্ম, কল বা ম্যানুয়াল এন্ট্রি থেকে লিড জমা হয়, আর সঠিক টিম মেম্বারকে অটো অ্যাসাইন হয় — কোনো লিড হারাবে না।'],
                    ['t' => 'ফলো-আপ রিমাইন্ডার (SMS/ইমেইল)', 'd' => 'কখন কাকে কল করতে হবে তা ভুলে যাওয়া বন্ধ করুন — SMS/ইমেইল রিমাইন্ডার আপনাকে মনে করিয়ে দেবে।'],
                    ['t' => 'কোটেশন ও ইনভয়েস তৈরি', 'd' => 'মিনিটে প্রফেশনাল কোটেশন ও ইনভয়েস তৈরি করুন, আর এক ক্লিকে গ্রাহককে পাঠান।'],
                    ['t' => 'পাইপলাইন ও স্টেজ ম্যানেজমেন্ট', 'd' => 'প্রতিটি লিড কোন পর্যায়ে আছে (নতুন → ফলো-আপ → কোটেশন → ক্লোজড) — এক নজরে দেখুন, কোনটা আটকে আছে ধরুন।'],
                    ['t' => 'টিম টার্গেট ও রিপোর্ট', 'd' => 'প্রতিটি সেলসপারসনের টার্গেট, অর্জন ও পারফরম্যান্স ট্র্যাক করুন — কে ভালো করছে, কাকে সাহায্য লাগবে তা পরিষ্কার।'],
                    ['t' => 'কল ও অ্যাক্টিভিটি লগ', 'd' => 'প্রতিটি কল, মিটিং ও ফলো-আপের ইতিহাস সংরক্ষিত থাকে — নতুন কেউ এলে পুরো প্রেক্ষাপট পেয়ে যায়।'],
                    ['t' => 'ক্লিক-টু-কল (IP ফোন)', 'd' => 'CRM থেকেই এক ক্লিকে গ্রাহককে কল করুন; কল রেকর্ডিংসহ সম্পূর্ণ অ্যাক্টিভিটি লগ থাকে।'],
                    ['t' => 'রিয়েল-টাইম ড্যাশবোর্ড', 'd' => 'লিড, সেলস ও রাজস্বের লাইভ চিত্র — সিদ্ধান্ত নিন মুহূর্তে, দিনের শেষে নয়।'],
                ],
                'features_en' => [
                    ['t' => 'Lead capture & assignment', 'd' => 'Leads come in from website forms, calls, or manual entry and are auto-assigned to the right team member — no lead gets lost.'],
                    ['t' => 'Follow-up reminders (SMS/email)', 'd' => 'Stop forgetting who to call and when — SMS/email reminders keep every follow-up on track.'],
                    ['t' => 'Quotation & invoice generation', 'd' => 'Create professional quotes and invoices in minutes and send them to the customer in one click.'],
                    ['t' => 'Pipeline & stage management', 'd' => 'See where every lead stands (new → follow-up → quote → closed) at a glance, and spot what\'s stuck.'],
                    ['t' => 'Team targets & reports', 'd' => 'Track each salesperson\'s target, achievement, and performance — clear who\'s winning and who needs help.'],
                    ['t' => 'Call & activity logging', 'd' => 'Every call, meeting, and follow-up is logged — a new team member inherits the full context.'],
                    ['t' => 'Click-to-call (IP phone)', 'd' => 'Call a customer right from the CRM in one click, with call recording and a complete activity log.'],
                    ['t' => 'Real-time dashboard', 'd' => 'A live view of leads, sales, and revenue — decide in the moment, not at day\'s end.'],
                ],
                'pricing_bn' => null,
                'pricing_en' => null,
                'faq_bn' => [
                    ['q' => 'লিড কোথা থেকে আসতে পারে?', 'a' => 'ওয়েবসাইট ফর্ম, ম্যানুয়াল এন্ট্রি, কল ও ইমেইল থেকে লিড সংগ্রহ করা যায়, আর সঠিক সেলসপারসনকে অটো অ্যাসাইন হয়।'],
                    ['q' => 'SMS পাঠানো যায়?', 'a' => 'হ্যাঁ, bulksmsbd গেটওয়ে ব্যবহার করে গ্রাহককে SMS পাঠানো যায়, আর ফলো-আপ রিমাইন্ডারও SMS-এ যায়।'],
                    ['q' => 'টিম মেম্বার যোগ করা যায়?', 'a' => 'হ্যাঁ, একাধিক ইউজার যোগ করে রোল ও পারমিশন দেওয়া যায় — কে কী দেখতে/করতে পারবে তা আপনি নিয়ন্ত্রণ করেন।'],
                    ['q' => 'ক্লিক-টু-কল কীভাবে কাজ করে?', 'a' => 'CRM-এর ভেতর থেকেই গ্রাহকের নম্বরে ক্লিক করলে কল যায় (IP ফোন), আর কল রেকর্ড ও অ্যাক্টিভিটি লগ সংরক্ষিত হয়।'],
                    ['q' => 'রিপোর্ট কি রিয়েল-টাইম?', 'a' => 'হ্যাঁ, লিড, সেলস ও টিম পারফরম্যান্সের রিয়েল-টাইম ড্যাশবোর্ড থাকে।'],
                    ['q' => 'পুরনো ডেটা কি ইমপোর্ট করা যাবে?', 'a' => 'হ্যাঁ, Excel থেকে লিড ও গ্রাহকের পুরনো ডেটা ইমপোর্ট করে দিই, শুরু করা সহজ।'],
                    ['q' => 'মোবাইল থেকে ব্যবহার করা যায়?', 'a' => 'হ্যাঁ, সম্পূর্ণ রেসপনসিভ — ফোন বা ট্যাবলেট থেকে লিড ও ফলো-আপ ম্যানেজ করা যায়।'],
                    ['q' => 'আমাদের ডেটা কি নিরাপদ?', 'a' => 'হ্যাঁ, আপনার সব লিড ও গ্রাহক ডেটা এনক্রিপ্টেড এবং নিয়মিত ব্যাকআপ হয়।'],
                ],
                'faq_en' => [
                    ['q' => 'Where can leads come from?', 'a' => 'Leads can be captured from website forms, manual entry, calls, and email, and auto-assigned to the right salesperson.'],
                    ['q' => 'Can SMS be sent?', 'a' => 'Yes, SMS can be sent to customers via the bulksmsbd gateway, and follow-up reminders go out by SMS too.'],
                    ['q' => 'Can I add team members?', 'a' => 'Yes, you can add multiple users with roles and permissions — you control what each person can see and do.'],
                    ['q' => 'How does click-to-call work?', 'a' => 'Click a customer\'s number inside the CRM to call (IP phone); the call and activity log are recorded.'],
                    ['q' => 'Are reports real-time?', 'a' => 'Yes, there is a real-time dashboard for leads, sales, and team performance.'],
                    ['q' => 'Can old data be imported?', 'a' => 'Yes, we import existing leads and customer data from Excel — easy to get started.'],
                    ['q' => 'Can it be used on mobile?', 'a' => 'Yes, fully responsive — manage leads and follow-ups from phone or tablet.'],
                    ['q' => 'Is our data secure?', 'a' => 'Yes, all your lead and customer data is encrypted and backed up regularly.'],
                ],
                'demo_url' => 'https://crm.regal-solution.com',
                'register_url' => 'https://crm.regal-solution.com/register',
                'login_url' => 'https://crm.regal-solution.com/login',
                'is_saas' => true,
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'slug' => 'mosque-management',
                'name_bn' => 'মসজিদ ম্যানেজমেন্ট',
                'name_en' => 'Mosque Management',
                'tagline_bn' => 'মসজিদের দান ও হিসাব স্বচ্ছ রাখুন',
                'tagline_en' => 'Keep your mosque\'s donations & accounts transparent',
                'summary_bn' => 'দান সংগ্রহ, খরচ হিসাব, কমিটি, মাদ্রাসা শিক্ষার্থী ও স্বচ্ছ রিপোর্ট — সব এক জায়গায়।',
                'summary_en' => 'Donation collection, expense accounting, committee, madrasa students, and transparent reports — all in one place.',
                'features_bn' => [
                    ['t' => 'দান ও চাঁদা সংগ্রহ', 'd' => 'ক্যাশ, মোবাইল ব্যাংকিং বা কার্ডে দান গ্রহণ করুন, প্রতিটি দানের রসিদ ও হিসাব অটো জমা হয়।'],
                    ['t' => 'জাকাত ও ফিতরা হিসাব', 'd' => 'জাকাত ও ফিতরার আলাদা খাত, আদায়ের রেকর্ড এবং বণ্টনের হিসাব — স্বচ্ছভাবে।'],
                    ['t' => 'আয়-ব্যয় লেজার', 'd' => 'প্রতিটি আয়-ব্যয় নির্দিষ্ট খাতে লিপিবদ্ধ হয়; মাসের শেষে সম্পূর্ণ লেজার ও ব্যালেন্স এক নজরে।'],
                    ['t' => 'কমিটি ব্যবস্থাপনা', 'd' => 'সভাপতি, সম্পাদক, কোষাধ্যক্ষসহ কমিটির সদস্যদের ভূমিকা ও মিটিং সিদ্ধান্ত ডিজিটাল রাখুন।'],
                    ['t' => 'মাদ্রাসা শিক্ষার্থী তালিকা', 'd' => 'মাদ্রাসার শিক্ষার্থী তালিকা, উপস্থিতি ও অগ্রগতি ট্র্যাক করুন — খাতার বদলে আঙুলের ডগায়।'],
                    ['t' => 'SMS নোটিশ', 'd' => 'জুমার খুতবা, ইফতার, ঈদ বা দানের ক্যাম্পেইনের খবর — মুসল্লিদের কাছে এক ক্লিকে SMS।'],
                    ['t' => 'স্বচ্ছ রিপোর্ট', 'd' => 'মাসিক আয়-ব্যয় রিপোর্ট PDF-এ প্রিন্ট বা শেয়ার করুন — মুসল্লিদের আস্থা ও স্বচ্ছতা বজায় থাকবে।'],
                    ['t' => 'কুরবানি ও প্রজেক্ট ফান্ড', 'd' => 'কুরবানি বা নির্মাণ তহবিলের আলাদা ক্যাম্পেইন চালান এবং দাতা ও অগ্রগতি ট্র্যাক করুন।'],
                    ['t' => 'অনলাইন দান (কিউআর/লিংক)', 'd' => 'মোবাইল ব্যাংকিং/কার্ডে অনলাইন দানের লিংক বা QR শেয়ার করুন — দূর থেকেও দান করা সহজ।'],
                ],
                'features_en' => [
                    ['t' => 'Donation & subscription collection', 'd' => 'Accept donations by cash, mobile banking, or card; every receipt and entry is logged automatically.'],
                    ['t' => 'Zakat & Fitra accounting', 'd' => 'Separate ledgers for Zakat and Fitra with collection records and transparent distribution.'],
                    ['t' => 'Income-expense ledger', 'd' => 'Every income and expense is recorded under a specific category; see the full ledger and balance at month end.'],
                    ['t' => 'Committee management', 'd' => 'Keep roles (president, secretary, treasurer) and meeting decisions digital.'],
                    ['t' => 'Madrasa student roster', 'd' => 'Track madrasa students, attendance, and progress — at your fingertips instead of in registers.'],
                    ['t' => 'SMS notices', 'd' => 'Jumu\'ah announcements, iftar, Eid, or donation campaigns — SMS to worshippers in one click.'],
                    ['t' => 'Transparent reports', 'd' => 'Print or share monthly income-expense reports as PDF — building trust and transparency.'],
                    ['t' => 'Qurbani & project funds', 'd' => 'Run separate campaigns for Qurbani or construction funds and track donors and progress.'],
                    ['t' => 'Online donations (QR/link)', 'd' => 'Share an online donation link or QR for mobile banking/card — easy to give from anywhere.'],
                ],
                'pricing_bn' => null,
                'pricing_en' => null,
                'faq_bn' => [
                    ['q' => 'দান কি অনলাইনে নেওয়া যায়?', 'a' => 'হ্যাঁ, মোবাইল ব্যাংকিং/কার্ডে অনলাইন দান নেওয়া যায়, আর QR কোড/লিংক শেয়ার করে দূর থেকেও দান নেওয়া যায়।'],
                    ['q' => 'রিপোর্ট কি সবার জন্য উন্মুক্ত?', 'a' => 'কমিটির সিদ্ধান্ত অনুযায়ী নির্দিষ্ট রিপোর্ট পাবলিক বা প্রাইভেট রাখা যায় — স্বচ্ছতা আর গোপনীয়তা দুটোই আপনার নিয়ন্ত্রণে।'],
                    ['q' => 'জাকাত ও ফিতরার আলাদা হিসাব রাখা যায়?', 'a' => 'হ্যাঁ, জাকাত, ফিতরা, দান ও প্রজেক্ট ফান্ডের আলাদা খাত থাকে, বণ্টনের হিসাবসহ।'],
                    ['q' => 'মাদ্রাসা শিক্ষার্থী ব্যবস্থাপনা আছে?', 'a' => 'হ্যাঁ, শিক্ষার্থী তালিকা, উপস্থিতি ও অগ্রগতি ট্র্যাক করা যায়।'],
                    ['q' => 'রিপোর্ট কি মুদ্রণযোগ্য?', 'a' => 'হ্যাঁ, মাসিক আয়-ব্যয় রিপোর্ট PDF বা প্রিন্ট করা যায়, মুসল্লিদের সাথে শেয়ার করার জন্য।'],
                    ['q' => 'পুরনো হিসাব কি আনা যাবে?', 'a' => 'হ্যাঁ, আমাদের টিম খাতা/Excel থেকে পুরনো দান ও খরচের হিসাব ইমপোর্ট করে দেয়।'],
                    ['q' => 'মোবাইল থেকে ব্যবহার করা যায়?', 'a' => 'হ্যাঁ, সম্পূর্ণ রেসপনসিভ — ফোন থেকে দান এন্ট্রি, খরচ ও রিপোর্ট দেখা যায়।'],
                    ['q' => 'আমাদের ডেটা কি নিরাপদ?', 'a' => 'হ্যাঁ, প্রতিটি মসজিদের ডেটা আলাদা ও এনক্রিপ্টেড, আর নিয়মিত ব্যাকআপ নেওয়া হয়।'],
                ],
                'faq_en' => [
                    ['q' => 'Can donations be collected online?', 'a' => 'Yes, online donations via mobile banking/card, plus QR/link sharing for remote giving.'],
                    ['q' => 'Are reports public?', 'a' => 'Per committee decision, specific reports can be kept public or private — transparency and privacy both under your control.'],
                    ['q' => 'Can Zakat and Fitra be tracked separately?', 'a' => 'Yes, separate ledgers for Zakat, Fitra, donations, and project funds, including distribution.'],
                    ['q' => 'Is madrasa student management included?', 'a' => 'Yes, student rosters, attendance, and progress can be tracked.'],
                    ['q' => 'Are reports printable?', 'a' => 'Yes, monthly income-expense reports can be exported as PDF or printed for sharing with worshippers.'],
                    ['q' => 'Can old records be imported?', 'a' => 'Yes, our team imports existing donation and expense records from ledgers/Excel.'],
                    ['q' => 'Can it be used on mobile?', 'a' => 'Yes, fully responsive — enter donations, expenses, and view reports from your phone.'],
                    ['q' => 'Is our data secure?', 'a' => 'Yes, each mosque\'s data is isolated and encrypted, with regular backups.'],
                ],
                'demo_url' => null,
                'register_url' => null,
                'login_url' => null,
                'is_saas' => true,
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'slug' => 'pos',
                'name_bn' => 'POS সফটওয়্যার',
                'name_en' => 'POS Software',
                'tagline_bn' => 'দ্রুত বিলিং, সহজ ইনভেন্টরি',
                'tagline_en' => 'Fast billing, simple inventory',
                'summary_bn' => 'দোকান ও রেস্তোরাঁর জন্য বিক্রি, স্টক, বাকি, ক্রয় ও গ্রাহক হিসাব — সব এক জায়গায়, নির্ভুলভাবে।',
                'summary_en' => 'Sales, stock, credit (baki), purchases, and customer accounts for shops and restaurants — all in one place, accurately.',
                'features_bn' => [
                    ['t' => 'বারকোড বিলিং ও রসিদ প্রিন্টিং', 'd' => 'স্ক্যান করে সেকেন্ডে বিল; কাস্টম লোগো-সহ রসিদ থার্মাল বা A4 প্রিন্টারে প্রিন্ট করুন।'],
                    ['t' => 'ইনভেন্টরি ও লো-স্টক অ্যালার্ট', 'd' => 'কোন পণ্য কত আছে, কবে শেষ হবে — লো-স্টক অ্যালার্টে আর হঠাৎ স্টক শেষ হবে না।'],
                    ['t' => 'বাকি ও ক্রেডিট হিসাব', 'd' => 'গ্রাহকের বাকি (বাকি খাতা) অটো ট্র্যাক হয়, আদায়ের রিমাইন্ডারসহ — বাকি আর ভুলবে না।'],
                    ['t' => 'ক্রয় ও সরবরাহকারী হিসাব', 'd' => 'কোন সরবরাহকারীর কাছে কী কেনা, কত বাকি — সব হিসাব এক জায়গায়।'],
                    ['t' => 'গ্রাহক হিসাব ও লয়্যালটি', 'd' => 'নিয়মিত গ্রাহকদের তথ্য ও কেনাকাটার ইতিহাস রাখুন, ডিসকাউন্ট/পয়েন্ট দিন।'],
                    ['t' => 'দৈনিক সেলস ড্যাশবোর্ড', 'd' => 'আজ কত বিক্রি, কোন পণ্য বেশি চলছে — লাইভ ড্যাশবোর্ডে এক নজরে।'],
                    ['t' => 'ক্যাশিয়ার ও মাল্টি-ইউজার রোল', 'd' => 'ক্যাশিয়ার, ম্যানেজার, অ্যাডমিন — কে কী করতে পারবে তা নিয়ন্ত্রণ করুন, দুর্নীতি কমবে।'],
                    ['t' => 'অফলাইন মোড', 'd' => 'ইন্টারনেট চলে গেলেও বিলিং বন্ধ হয় না; সংযোগ ফিরলে সব সিঙ্ক হয়ে যায়।'],
                ],
                'features_en' => [
                    ['t' => 'Barcode billing & receipt printing', 'd' => 'Scan and bill in seconds; print receipts with your custom logo on thermal or A4 printers.'],
                    ['t' => 'Inventory & low-stock alerts', 'd' => 'See what you have and what\'s running out — low-stock alerts prevent sudden stockouts.'],
                    ['t' => 'Credit (baki) accounting', 'd' => 'Customer credit is tracked automatically with collection reminders — never lose track of baki again.'],
                    ['t' => 'Purchase & supplier accounts', 'd' => 'What you bought from which supplier and how much you owe — all in one place.'],
                    ['t' => 'Customer accounts & loyalty', 'd' => 'Keep regular customers\' info and purchase history; offer discounts or points.'],
                    ['t' => 'Daily sales dashboard', 'd' => 'Today\'s sales and best-sellers at a glance on a live dashboard.'],
                    ['t' => 'Cashier & multi-user roles', 'd' => 'Control what cashiers, managers, and admins can do — reducing leakage.'],
                    ['t' => 'Offline mode', 'd' => 'Billing keeps working when the internet drops; everything syncs when the connection returns.'],
                ],
                'pricing_bn' => null,
                'pricing_en' => null,
                'faq_bn' => [
                    ['q' => 'ইন্টারনেট না থাকলে কাজ হবে?', 'a' => 'হ্যাঁ, অফলাইন মোডে বিলিং চলে এবং সংযোগ ফিরলে সব ডেটা স্বয়ংক্রিয়ভাবে সিঙ্ক হয়।'],
                    ['q' => 'কোন প্রিন্টার লাগবে?', 'a' => 'থার্মাল প্রিন্টার ও A4 প্রিন্টার দুটোই সমর্থিত — আপনার যা আছে তাই চলবে।'],
                    ['q' => 'বারকোড স্ক্যানার লাগবে?', 'a' => 'চাইলে যেকোনো USB বারকোড স্ক্যানার সংযোগ করা যায়, আবার স্ক্যানার ছাড়াও প্রোডাক্ট সার্চ করে বিল করা যায়।'],
                    ['q' => 'বাকি (ক্রেডিট) বিক্রি ট্র্যাক হয়?', 'a' => 'হ্যাঁ, প্রতিটি গ্রাহকের বাকি অটো হিসাব হয়, আর আদায়ের রিমাইন্ডারসহ সম্পূর্ণ খাতা থাকে।'],
                    ['q' => 'একাধিক শাখা চালানো যায়?', 'a' => 'হ্যাঁ, একাধিক আউটলেটের সেন্ট্রাল ইনভেন্টরি ও রিপোর্ট একসাথে দেখা যায়।'],
                    ['q' => 'ক্যাশিয়ারকে সীমিত অ্যাক্সেস দেওয়া যায়?', 'a' => 'হ্যাঁ, রোল-ভিত্তিক পারমিশন — কে ছাড় দিতে পারবে, কে রিফান্ড দিতে পারবে তা আপনি ঠিক করবেন।'],
                    ['q' => 'প্রতিদিনের রিপোর্ট কী কী পাওয়া যায়?', 'a' => 'দৈনিক সেলস, ইনভেন্টরি, বাকি আদায়, লাভ-লোকসান ও সেরা পণ্যের রিপোর্ট পাওয়া যায়।'],
                    ['q' => 'পুরনো স্টক ডেটা কি আনা যাবে?', 'a' => 'হ্যাঁ, Excel থেকে পুরনো পণ্য ও স্টক ডেটা ইমপোর্ট করে দিই।'],
                ],
                'faq_en' => [
                    ['q' => 'Does it work without internet?', 'a' => 'Yes, billing works in offline mode and all data syncs automatically when the connection returns.'],
                    ['q' => 'Which printers are supported?', 'a' => 'Both thermal and A4 printers are supported — use whatever you have.'],
                    ['q' => 'Do I need a barcode scanner?', 'a' => 'Any USB barcode scanner can be connected, or you can search products and bill without one.'],
                    ['q' => 'Is credit (baki) sales tracked?', 'a' => 'Yes, each customer\'s credit is accounted automatically, with a full ledger and collection reminders.'],
                    ['q' => 'Can I run multiple outlets?', 'a' => 'Yes, central inventory and reports across multiple outlets are supported.'],
                    ['q' => 'Can cashiers be given limited access?', 'a' => 'Yes, role-based permissions let you decide who can discount or refund.'],
                    ['q' => 'What daily reports are available?', 'a' => 'Daily sales, inventory, credit collection, profit-loss, and best-seller reports.'],
                    ['q' => 'Can old stock data be imported?', 'a' => 'Yes, we import existing product and stock data from Excel.'],
                ],
                'demo_url' => 'https://pos.regal-solution.com',
                'register_url' => 'https://pos.regal-solution.com/register',
                'login_url' => 'https://pos.regal-solution.com/login',
                'is_saas' => true,
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'slug' => 'bus-ticket',
                'name_bn' => 'বাস টিকেট বুকিং',
                'name_en' => 'Bus Ticket Booking',
                'tagline_bn' => 'সিট ম্যাপ, কাউন্টার ও ফ্লিট ম্যানেজমেন্ট',
                'tagline_en' => 'Seat maps, counters & fleet management',
                'summary_bn' => 'অনলাইন বুকিং, সিট ম্যাপ, মাল্টি-কাউন্টার নেটওয়ার্ক, ফ্লিট ও দৈনিক আর্থিক সমাপ্তি — সব স্বয়ংক্রিয়।',
                'summary_en' => 'Online booking, seat maps, multi-counter networks, fleet management, and daily financial closing — all automated.',
                'features_bn' => [
                    ['t' => 'সিট-ভিত্তিক বুকিং ও QR ই-টিকেট', 'd' => 'যাত্রী ইন্টারেক্টিভ সিট ম্যাপে সিট বেছে নেয়, আর ইউনিক QR ই-টিকেট অটো তৈরি হয় — বোর্ডিংয়ে স্ক্যান করলেই যাচাই।'],
                    ['t' => 'রুট ও ট্রিপ ব্যবস্থাপনা', 'd' => 'রুট, স্টপ ও প্রতি-স্টপ ভাড়া সেট করুন; সাপ্তাহিক সময়সূচি থেকে এক ক্লিকে ট্রিপ তৈরি করুন।'],
                    ['t' => 'মাল্টি-কাউন্টার নেটওয়ার্ক', 'd' => 'শহরজুড়ে একাধিক কাউন্টার চালান, কোন কর্মী কোন রুট বুক করতে পারবে তা নিয়ন্ত্রণ করুন, রাজস্ব আলাদা ট্র্যাক করুন।'],
                    ['t' => 'ফ্লিট ও ড্রাইভার রোস্টার', 'd' => 'বাস, চালক, হেলপার ও সুপারভাইজারের তথ্য ও রোস্টার ম্যানেজ করুন — কে কোন বাসে, কবে, সব পরিষ্কার।'],
                    ['t' => 'দৈনিক আর্থিক সমাপ্তি', 'd' => 'প্রতিটি কাউন্টারে দিন শেষে প্রত্যাশিত ও সংগৃহীত নগদ মিলিয়ে দেখুন; অনুমোদনের পর দিন লক করুন — হেরফের অসম্ভব।'],
                    ['t' => 'রাজস্ব রিপোর্ট ও অ্যানালিটিক্স', 'd' => 'রুট অনুযায়ী রাজস্ব, সিট দখল হার, খরচ ও কাউন্টার কালেকশন — সব রিপোর্ট রপ্তানিযোগ্য।'],
                    ['t' => 'যাত্রী আইডি যাচাই', 'd' => 'বুকিংয়ে NID/পাসপোর্ট দিয়ে যাত্রী যাচাই — নিরাপত্তা ও জবাবদিহি বাড়ে।'],
                    ['t' => 'একাধিক পেমেন্ট পদ্ধতি', 'd' => 'নগদ, বিকাশ/নগদ বা কার্ড — যাত্রীর সুবিধামতো পেমেন্ট নিন, সব হিসাব অটো।'],
                    ['t' => 'রোল-ভিত্তিক অ্যাক্সেস', 'd' => 'সুপার অ্যাডমিন, ম্যানেজার, কাউন্টার স্টাফ — প্রত্যেকে শুধু নিজের কাজ দেখে, পুরো সিস্টেমে নিয়ন্ত্রণ আপনার।'],
                ],
                'features_en' => [
                    ['t' => 'Seat-wise booking & QR e-tickets', 'd' => 'Passengers pick seats on an interactive seat map; a unique QR e-ticket is generated and verified by scanning at boarding.'],
                    ['t' => 'Route & trip management', 'd' => 'Set routes, stops, and per-stop fares; generate trips from weekly schedules in one click.'],
                    ['t' => 'Multi-counter network', 'd' => 'Run multiple counters across the city, control which staff can book which routes, and track revenue separately.'],
                    ['t' => 'Fleet & driver roster', 'd' => 'Manage buses, drivers, helpers, and supervisors with clear rosters — who\'s on which bus, when.'],
                    ['t' => 'Daily financial closing', 'd' => 'Reconcile expected vs collected cash at each counter daily; lock the day after approval — discrepancies become impossible.'],
                    ['t' => 'Revenue reports & analytics', 'd' => 'Revenue by route, seat occupancy, expenses, and counter collections — all exportable.'],
                    ['t' => 'Passenger ID verification', 'd' => 'Verify passengers with NID/passport at booking — stronger security and accountability.'],
                    ['t' => 'Multiple payment methods', 'd' => 'Cash, bKash/Nagad, or card — take payment however passengers prefer, with automatic accounting.'],
                    ['t' => 'Role-based access', 'd' => 'Super admin, manager, and counter staff each see only their own work — you keep full control.'],
                ],
                'pricing_bn' => null,
                'pricing_en' => null,
                'faq_bn' => [
                    ['q' => 'যাত্রী কি অনলাইনে টিকেট কাটতে পারবেন?', 'a' => 'হ্যাঁ, যাত্রী ওয়েব বা অ্যাপে সিট বেছে নিয়ে অনলাইনে টিকেট কিনতে পারবেন, আর QR ই-টিকেট পাবেন।'],
                    ['q' => 'QR টিকেট কীভাবে কাজ করে?', 'a' => 'প্রতিটি বুকিংয়ে ইউনিক QR কোড তৈরি হয়; বোর্ডিং স্টাফ স্ক্যান করে যাচাই করে — নকল টিকেট আটকায়।'],
                    ['q' => 'ওভারবুকিংয়ের সমস্যা হয়?', 'a' => 'না, আমাদের সিস্টেম একই সিটে দুইবার বুকিং আটকায় (ডেটাবেস-লেভেল লক), তাই ওভারবুকিং অসম্ভব।'],
                    ['q' => 'মোবাইলে ব্যবহার করা যায়?', 'a' => 'হ্যাঁ, সম্পূর্ণ রেসপনসিভ — ফোন বা ট্যাবলেট থেকে কাউন্টার চালানো যায়।'],
                    ['q' => 'দৈনিক সমাপ্তি কীভাবে হয়?', 'a' => 'প্রতিটি কাউন্টার দিন শেষে প্রত্যাশিত ও সংগৃহীত নগদ মিলিয়ে জমা দেয়; ম্যানেজার অনুমোদন করলে দিন লক হয়।'],
                    ['q' => 'কী কী রিপোর্ট পাওয়া যায়?', 'a' => 'দৈনিক সমাপ্তি, রুট-ভিত্তিক রাজস্ব, সিট দখল হার, খরচ ও কাউন্টার কালেকশনের রিপোর্ট পাওয়া যায়।'],
                    ['q' => 'একাধিক কাউন্টার একসাথে চালানো যায়?', 'a' => 'হ্যাঁ, মাল্টি-কাউন্টার নেটওয়ার্ক — কোন কর্মী কোন রুট বুক করতে পারবে তা নিয়ন্ত্রণ করে রাজস্ব আলাদা ট্র্যাক হয়।'],
                    ['q' => 'আমাদের ডেটা কি নিরাপদ?', 'a' => 'হ্যাঁ, প্রতিটি অপারেটরের ডেটা আলাদা (multi-tenant), এনক্রিপ্টেড এবং নিয়মিত অফসাইট ব্যাকআপ হয়।'],
                ],
                'faq_en' => [
                    ['q' => 'Can passengers book online?', 'a' => 'Yes, passengers choose seats and buy tickets online via web or app, receiving a QR e-ticket.'],
                    ['q' => 'How does QR ticketing work?', 'a' => 'Each booking gets a unique QR code that boarding staff scan to verify — preventing fake tickets.'],
                    ['q' => 'Can overbooking happen?', 'a' => 'No, our system blocks double-booking of the same seat at the database level, making overbooking impossible.'],
                    ['q' => 'Can it be used on mobile?', 'a' => 'Yes, fully responsive — counters run on phones and tablets.'],
                    ['q' => 'How does daily closing work?', 'a' => 'Each counter reconciles expected vs collected cash at day end; the manager approves and the day locks.'],
                    ['q' => 'What reports are available?', 'a' => 'Daily closing, route revenue, seat occupancy, expenses, and counter collection reports.'],
                    ['q' => 'Can multiple counters run together?', 'a' => 'Yes, a multi-counter network controls which staff book which routes and tracks revenue separately.'],
                    ['q' => 'Is our data secure?', 'a' => 'Yes, each operator\'s data is isolated (multi-tenant), encrypted, and backed up offsite regularly.'],
                ],
                'demo_url' => 'https://bus.regal-solution.com',
                'register_url' => 'https://bus.regal-solution.com/register',
                'login_url' => 'https://bus.regal-solution.com/login',
                'is_saas' => true,
                'sort_order' => 6,
                'is_active' => true,
            ],
            [
                'slug' => 'ecommerce-website',
                'name_bn' => 'ই-কমার্স ওয়েবসাইট',
                'name_en' => 'E-commerce Website',
                'tagline_bn' => 'আপনার ব্যবসার জন্য সম্পূর্ণ অনলাইন স্টোর',
                'tagline_en' => 'A complete online store for your business',
                'summary_bn' => 'কাস্টম ডিজাইনের ই-কমার্স সাইট — প্রোডাক্ট, কার্ট, পেমেন্ট ও অর্ডার ম্যানেজমেন্টসহ, শুরু থেকে শেষ পর্যন্ত।',
                'summary_en' => 'A custom-designed e-commerce site with products, cart, payments, and order management — end to end.',
                'features_bn' => [
                    ['t' => 'কাস্টম রেসপনসিভ ডিজাইন', 'd' => 'আপনার ব্র্যান্ড অনুযায়ী ইউনিক ডিজাইন, যা ফোন, ট্যাবলেট ও কম্পিউটারে নিখুঁত দেখায়।'],
                    ['t' => 'প্রোডাক্ট ক্যাটালগ ও ক্যাটাগরি', 'd' => 'সীমাহীন প্রোডাক্ট, ক্যাটাগরি ও ভ্যারিয়েশন (সাইজ/কালার) — সহজে ম্যানেজ করার অ্যাডমিন প্যানেল।'],
                    ['t' => 'কার্ট ও চেকআউট', 'd' => 'দ্রুত কার্ট ও সহজ চেকআউট — যত কম ধাপ, তত বেশি অর্ডার কমপ্লিট হয়।'],
                    ['t' => 'বিকাশ/নগদ/কার্ড পেমেন্ট', 'd' => 'বাংলাদেশের সব জনপ্রিয় পেমেন্ট গেটওয়ে ইন্টিগ্রেটেড — গ্রাহক যেভাবে চায় সেভাবে পেমেন্ট করুক।'],
                    ['t' => 'অর্ডার ও ডেলিভারি ম্যানেজমেন্ট', 'd' => 'অর্ডার স্ট্যাটাস, স্টক আপডেট ও ডেলিভারি ট্র্যাকিং — সব এক ড্যাশবোর্ডে।'],
                    ['t' => 'SEO অপটিমাইজড', 'd' => 'গুগলে সহজে খুঁজে পাওয়া যায় এমন স্ট্রাকচার — অর্গানিক ট্রাফিক ও সেলস বাড়ে।'],
                    ['t' => 'কুপন ও ডিসকাউন্ট', 'd' => 'প্রোমো কোড, ডিসকাউন্ট ও ফ্ল্যাশ সেল চালান — বিক্রি বাড়ানোর টুলসহ।'],
                    ['t' => 'রিপোর্ট ও অ্যানালিটিক্স', 'd' => 'কোন প্রোডাক্ট বিক্রি হচ্ছে, কত রাজস্ব আসছে — ডেটা দেখে ব্যবসা বাড়ান।'],
                ],
                'features_en' => [
                    ['t' => 'Custom responsive design', 'd' => 'A unique design matched to your brand that looks perfect on phone, tablet, and desktop.'],
                    ['t' => 'Product catalog & categories', 'd' => 'Unlimited products, categories, and variations (size/color) with an easy admin panel.'],
                    ['t' => 'Cart & checkout', 'd' => 'Fast cart and simple checkout — the fewer the steps, the more orders completed.'],
                    ['t' => 'bKash/Nagad/card payments', 'd' => 'All popular Bangladeshi payment gateways integrated — let customers pay however they prefer.'],
                    ['t' => 'Order & delivery management', 'd' => 'Order status, stock updates, and delivery tracking — all in one dashboard.'],
                    ['t' => 'SEO optimized', 'd' => 'A structure that ranks on Google — driving organic traffic and sales.'],
                    ['t' => 'Coupons & discounts', 'd' => 'Run promo codes, discounts, and flash sales with built-in tools to grow sales.'],
                    ['t' => 'Reports & analytics', 'd' => 'See what\'s selling and how much you\'re earning — grow with data.'],
                ],
                'pricing_bn' => null,
                'pricing_en' => null,
                'faq_bn' => [
                    ['q' => 'কত সময়ে ওয়েবসাইট তৈরি হবে?', 'a' => 'সাধারণত ২–৪ সপ্তাহে সম্পূর্ণ সাইট ডেলিভারি করা হয়, চাহিদার জটিলতার উপর নির্ভর করে।'],
                    ['q' => 'পেমেন্ট গেটওয়ে যুক্ত করা যায়?', 'a' => 'হ্যাঁ, বিকাশ, নগদ ও কার্ড পেমেন্ট ইন্টিগ্রেশন করা হয় — আর চাইলে অন্যান্য গেটওয়েও।'],
                    ['q' => 'কন্টেন্ট কি নিজেই আপডেট করতে পারব?', 'a' => 'হ্যাঁ, অ্যাডমিন প্যানেল থেকে প্রোডাক্ট, দাম, ছবি ও কন্টেন্ট নিজেই ম্যানেজ করতে পারবেন — কোডিং লাগবে না।'],
                    ['q' => 'হোস্টিং ও ডোমেইন কে দেবে?', 'a' => 'আমরা ডোমেইন কেনা, হোস্টিং সেটআপ ও SSL-সহ সম্পূর্ণ সেটআপে সহায়তা করি।'],
                    ['q' => 'ডেলিভারি চার্জ ও এরিয়া ভিত্তিক সেটআপ আছে?', 'a' => 'হ্যাঁ, এরিয়া/জেলা অনুযায়ী আলাদা ডেলিভারি চার্জ ও ক্যাশ-অন-ডেলিভারি সেট করা যায়।'],
                    ['q' => 'মোবাইলে ভালো দেখাবে?', 'a' => 'হ্যাঁ, সম্পূর্ণ রেসপনসিভ — মোবাইলেই সবচেয়ে বেশি কেনাকাটা হয় বলে আমরা মোবাইল-ফার্স্ট ডিজাইন করি।'],
                    ['q' => 'SEO করা থাকবে?', 'a' => 'হ্যাঁ, প্রতিটি পেজ SEO-অপটিমাইজড, যাতে গুগলে আপনার প্রোডাক্ট সহজে খুঁজে পাওয়া যায়।'],
                    ['q' => 'পরে ফিচার যোগ করা যাবে?', 'a' => 'হ্যাঁ, ভবিষ্যতে নতুন ফিচার, পেমেন্ট বা ইন্টিগ্রেশন যোগ করা সহজ — সিস্টেমটা বাড়ানোর উপযোগী করে বানানো হয়।'],
                ],
                'faq_en' => [
                    ['q' => 'How long does it take?', 'a' => 'Typically 2–4 weeks depending on complexity.'],
                    ['q' => 'Can payment gateways be integrated?', 'a' => 'Yes, bKash, Nagad, and card payments are integrated — plus other gateways on request.'],
                    ['q' => 'Can I update content myself?', 'a' => 'Yes, you manage products, prices, images, and content from the admin panel — no coding needed.'],
                    ['q' => 'Who provides hosting and domain?', 'a' => 'We assist fully with domain purchase, hosting setup, and SSL.'],
                    ['q' => 'Is area-based delivery supported?', 'a' => 'Yes, per-area/district delivery charges and cash-on-delivery can be configured.'],
                    ['q' => 'Will it look good on mobile?', 'a' => 'Yes, fully responsive — we design mobile-first since most purchases happen on phones.'],
                    ['q' => 'Is SEO included?', 'a' => 'Yes, every page is SEO-optimized so your products rank on Google.'],
                    ['q' => 'Can features be added later?', 'a' => 'Yes, adding new features, payments, or integrations later is easy — the system is built to scale.'],
                ],
                'demo_url' => null,
                'register_url' => null,
                'login_url' => null,
                'is_saas' => false,
                'sort_order' => 7,
                'is_active' => true,
            ],
            [
                'slug' => 'custom-software',
                'name_bn' => 'কাস্টম সফটওয়্যার ও ওয়েবসাইট',
                'name_en' => 'Custom Software & Website Development',
                'tagline_bn' => 'আপনার চাহিদা অনুযায়ী সফটওয়্যার ও ওয়েবসাইট',
                'tagline_en' => 'Software & websites built to your exact needs',
                'summary_bn' => 'আপনার ব্যবসার নির্দিষ্ট সমস্যার জন্য কাস্টম ওয়েব/মোবাইল সফটওয়্যার এবং প্রফেশনাল ওয়েবসাইট — শুরু থেকে ডেলিভারি পর্যন্ত।',
                'summary_en' => 'Custom web/mobile software and professional websites for your business\'s specific problems — from start to delivery.',
                'features_bn' => [
                    ['t' => 'রিকোয়ারমেন্ট অ্যানালাইসিস', 'd' => 'প্রথমে আপনার সমস্যাটা ভালোভাবে বুঝি — কী দরকার, কী দরকার নেই — তারপর সঠিক সমাধান ডিজাইন করি।'],
                    ['t' => 'কাস্টম ওয়েব ও মোবাইল অ্যাপ', 'd' => 'অফ-দ্য-শেলফ নয়; আপনার ওয়ার্কফ্লো অনুযায়ী কাস্টম ওয়েব অ্যাপ বা মোবাইল অ্যাপ বানাই।'],
                    ['t' => 'প্রফেশনাল ওয়েবসাইট', 'd' => 'বিজনেস, পোর্টফোলিও বা ল্যান্ডিং পেজ — ব্র্যান্ড অনুযায়ী দ্রুত, রেসপনসিভ ও SEO-অপটিমাইজড ওয়েবসাইট।'],
                    ['t' => 'API ও থার্ড-পার্টি ইন্টিগ্রেশন', 'd' => 'পেমেন্ট গেটওয়ে, SMS, ডেলিভারি বা অন্য যেকোনো সিস্টেমের সাথে ইন্টিগ্রেশন।'],
                    ['t' => 'রিপোর্টিং ও ড্যাশবোর্ড', 'd' => 'আপনার ব্যবসার মূল মেট্রিক্সের লাইভ ড্যাশবোর্ড ও রিপোর্ট — ডেটা-চালিত সিদ্ধান্ত।'],
                    ['t' => 'নিরাপদ ও স্কেলেবল আর্কিটেকচার', 'd' => 'ব্যবসা বাড়লেও সিস্টেম যেন বাড়ে — নিরাপদ ও স্কেলেবল ডিজাইন, ভবিষ্যতে ফিচার যোগ করা সহজ।'],
                    ['t' => 'ট্রেনিং ও সাপোর্ট', 'd' => 'ডেলিভারির পর আপনার টিমকে প্রশিক্ষণ দিই, আর চলমান সাপোর্টে পাশে থাকি।'],
                    ['t' => 'আপডেট ও মেইনটেন্যান্স', 'd' => 'নিয়মিত আপডেট, বাগ ফিক্স ও নিরাপত্তা প্যাচ — সিস্টেম সবসময় চালু ও সুরক্ষিত।'],
                    ['t' => 'স্বচ্ছ প্রসেস ও কমিউনিকেশন', 'd' => 'প্রতিটি ধাপে আপডেট পাবেন — কোনো অস্বচ্ছতা নয়, সময়মতো ডেলিভারি।'],
                ],
                'features_en' => [
                    ['t' => 'Requirement analysis', 'd' => 'We understand your problem first — what\'s needed and what isn\'t — then design the right solution.'],
                    ['t' => 'Custom web & mobile apps', 'd' => 'Not off-the-shelf; we build custom web or mobile apps around your workflow.'],
                    ['t' => 'Professional websites', 'd' => 'Business, portfolio, or landing pages — fast, responsive, SEO-optimized websites matched to your brand.'],
                    ['t' => 'API & third-party integration', 'd' => 'Integration with payment gateways, SMS, delivery, or any other system.'],
                    ['t' => 'Reporting & dashboards', 'd' => 'Live dashboards and reports for your key metrics — data-driven decisions.'],
                    ['t' => 'Secure & scalable architecture', 'd' => 'Secure and scalable design that grows with your business — easy to add features later.'],
                    ['t' => 'Training & support', 'd' => 'We train your team after delivery and stay alongside you with ongoing support.'],
                    ['t' => 'Updates & maintenance', 'd' => 'Regular updates, bug fixes, and security patches — your system stays up and protected.'],
                    ['t' => 'Transparent process & communication', 'd' => 'You get updates at every step — no opacity, on-time delivery.'],
                ],
                'pricing_bn' => null,
                'pricing_en' => null,
                'faq_bn' => [
                    ['q' => 'কত খরচ হবে?', 'a' => 'প্রজেক্টের স্কেল ও ফিচারের উপর খরচ নির্ভর করে। প্রথমে ফ্রি কনসালটেশন নিন — আমরা চাহিদা বুঝে নির্দিষ্ট কোটেশন দেব।'],
                    ['q' => 'কত সময় লাগে?', 'a' => 'ছোট ওয়েবসাইট ২–৪ সপ্তাহ, বড় সফটওয়্যার ২–৮ সপ্তাহ বা তার বেশি — স্কেল অনুযায়ী।'],
                    ['q' => 'সোর্স কোড কি আমি পাব?', 'a' => 'হ্যাঁ, চুক্তি অনুযায়ী সোর্স কোড, ডকুমেন্টেশন ও অ্যাক্সেস সম্পূর্ণ আপনার কাছে ডেলিভারি করা হয়।'],
                    ['q' => 'সাপোর্ট ও মেইনটেন্যান্স দেওয়া হয়?', 'a' => 'হ্যাঁ, ডেলিভারির পর ট্রেনিং, চলমান সাপোর্ট ও নিয়মিত মেইনটেন্যান্স/আপডেট দেওয়া হয়।'],
                    ['q' => 'আমার ব্যবসায় কী দরকার তা না জানলে?', 'a' => 'সমস্যা নেই — ফ্রি কনসালটেশনে আমরা আপনার ওয়ার্কফ্লো বুঝে সেরা সমাধান সাজেস্ট করব, বাধ্যবাধকতা ছাড়া।'],
                    ['q' => 'মোবাইল অ্যাপও কি বানিয়ে দেন?', 'a' => 'হ্যাঁ, ওয়েবের পাশাপাশি অ্যান্ড্রয়েড/iOS অ্যাপ বা PWA (ইনস্টলযোগ্য ওয়েব অ্যাপ) বানাই।'],
                    ['q' => 'ডেটা কি নিরাপদ থাকবে?', 'a' => 'হ্যাঁ, আমরা এনক্রিপশন, ব্যাকআপ ও নিরাপত্তা বেস্ট-প্র্যাকটিস মেনে ডেভেলপ করি।'],
                    ['q' => 'কাজের অগ্রগতি কীভাবে দেখব?', 'a' => 'প্রতিটি ধাপে ডেমো ও আপডেট পাবেন; ফিডব্যাক অনুযায়ী আমরা সামঞ্জস্য করি।'],
                ],
                'faq_en' => [
                    ['q' => 'How much does it cost?', 'a' => 'Cost depends on scope and features. Get a free consultation — we\'ll give a concrete quote once we understand your needs.'],
                    ['q' => 'How long does it take?', 'a' => 'Small websites 2–4 weeks; larger software 2–8 weeks or more, depending on scope.'],
                    ['q' => 'Will I get the source code?', 'a' => 'Yes, per the agreement, source code, documentation, and access are fully delivered to you.'],
                    ['q' => 'Is support and maintenance provided?', 'a' => 'Yes, post-delivery training, ongoing support, and regular maintenance/updates are provided.'],
                    ['q' => 'What if I don\'t know exactly what I need?', 'a' => 'No problem — in a free consultation we understand your workflow and suggest the best solution, with no obligation.'],
                    ['q' => 'Do you build mobile apps too?', 'a' => 'Yes, alongside web we build Android/iOS apps or PWAs (installable web apps).'],
                    ['q' => 'Will my data be secure?', 'a' => 'Yes, we develop with encryption, backups, and security best practices.'],
                    ['q' => 'How do I track progress?', 'a' => 'You get demos and updates at every step, and we adjust based on your feedback.'],
                ],
                'demo_url' => null,
                'register_url' => null,
                'login_url' => null,
                'is_saas' => false,
                'sort_order' => 8,
                'is_active' => true,
            ],
        ];

        foreach ($products as $data) {
            Product::query()->updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
